# Basic
title = "Yuheng Wu ツ"
baseURL = "https://ustchenry.github.io/"
theme = "vno-hugo"

# supported languages: en-us, zh-cn (lowercase language codes only)
defaultContentLanguage = 'en-us'
# here lists available languages, if you wish to add your own custom translation, please refer to https://gohugo.io/content-management/multilingual
[languages]
  [languages.en-us]
    languageName = 'English(United States)'
    weight = 10
  [languages.zh-cn]
    languageName = '简体中文（中国大陆）'
    weight = 20

# Pagination
# paginate = 10
# paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  url = "https://ustchenry.github.io"
  weight = 5
  [[menu.main]]
    name = "Profile"
    identifier = "profile"
    url = "/Profile/"
    weight = 10
  [[menu.main]]
  name = "Publications"
  identifier = "publications"
  url = "/Publications/"
  weight = 15
  [[menu.main]]
  name = "Moments"
  identifier = "moments"
  url = ""
  weight = 17
  [[menu.main]]
    name = "Tags"
    identifier = "Tags"
#    url = "/tags/"
    weight = 20
[taxonomies]
    tag = "tags"
    
[params]
author = "Yuheng Wu"
subtitle = "Hi there~"
description = "If you want a happy ending, that depends on where you stop your story."
welcomeMessage = ""

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = ""

[params.comment]
disqus = "Henry"
duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
github = "ustchenry"
twitter = "wu_yuheng1079"
facebook = "profile.php?id=100026153963941"
instagram = "henry1433223/"
googlescholar = "citations?hl=en&view_op=list_works&gmla=AKKJWFeARdLijamI6s5WBLcLI6gFfWiyegQ8TjkIBbo2MMnSBqWOjZ7s2-asujBMsfMwjEkOCuXpmwj1uz0b7A&user=jfXiHv4AAAAJ"
mail = "wuyuheng@mit.edu"
linkedin = "%E5%AE%87%E6%A1%81-%E5%90%B4-6683302bb/"
pingpong = "181272?uai=181272&embedded=&max=20"
weibo = "7527380558?t=&luicode=10000011&lfid=100103type%3D1%26q%3DHenry1993"

[params.ga]
ID = "your_ga_id"
host = "your_host"

[params.blogButton]
title = "Blog"
description = "Visit blog"


[params.copyright]
license = 'CC BY-NC-SA 4.0'
license_link = 'http://creativecommons.org/licenses/by-nc-sa/4.0/'

[permalinks]
posts = "/:year/:month/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
