# Basic
title = "Henry ツ"
baseURL = "https://ustchenry.github.io/"
theme = "vno-hugo"

# supported languages: en-us, zh-cn (lowercase language codes only)
defaultContentLanguage = 'en-us'
# here lists available languages, if you wish to add your own custom translation, please refer to https://gohugo.io/content-management/multilingual
[languages]
  [languages.en-us]
    languageName = 'English(United States)'
    weight = 10
  [languages.zh-cn]
    languageName = '简体中文（中国大陆）'
    weight = 20

# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  url = "https://ustchenry.github.io"
  weight = 5
  [[menu.main]]
    name = "Profile"
    identifier = "profile"
    url = "/Profile/"
    weight = 10
  [[menu.main]]
  name = "Publications"
  identifier = "publications"
  url = ""
  weight = 15
  [[menu.main]]
  name = "Moments"
  identifier = "moments"
  url = ""
  weight = 17
  [[menu.main]]
    name = "Tags"
    identifier = "Tags"
    url = "/tags/"
    weight = 20
[taxonomies]
    tag = "tags"
    
[params]
author = "Henry"
subtitle = "Yuheng Wu"
description = "Hi there ~"
welcomeMessage = ""

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = ""

[params.comment]
disqus = "Henry"
duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
weibo = " "
github = "ustchenry"
twitter = " "
gplus = " "
mail = "yw210@rice.edu"
linkedin = " "

[params.ga]
ID = "your_ga_id"
host = "your_host"

[params.blogButton]
title = "Blog"
description = "Visit blog"


[params.copyright]
license = 'CC BY-NC-SA 4.0'
license_link = 'http://creativecommons.org/licenses/by-nc-sa/4.0/'

[permalinks]
posts = "/:year/:month/:title/"
